name: Python Build and Test
on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Start Selenium Server HUB
        run: nohup java -jar selenium-server-4.17.0.jar hub & sleep 10
        shell: bash

      - name: Start Selenium Server nodes
        run: nohup java -jar selenium-server-4.17.0.jar node --port 5555 --selenium-manager true & sleep 10
        shell: bash

      - name: Install requirements
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Run Test
        run: |
          pip install pytest pytest-html
          python -m pytest test/api_and_ui/test_ui_and_api.py --html=report.html


      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: report.html